name: Go

on:
  push:
    tags:
    - 'v*'

jobs:
  build-linux:
    strategy:
      matrix: 
        arch: [amd64, arm64, arm]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      env:
        GOOS: linux
        GOARCH: ${{ matrix.arch }}
      run: go build -o ./bin/linux-${{ matrix.arch }}/sc-bot ./cmd/
    - name: Package
      run: |
        tar -czvf ./bin/sc-bot-linux-${{ matrix.arch }}.tar.gz ./bin/linux-${{ matrix.arch }}/sc-bot ./CHANGELOG.md ./README.md ./settings.example.toml

  setup-release:
    runs-on: ubuntu-latest
    needs: build-linux
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./bin/*.tar.gz"
