name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    strategy:
      matrix: 
        arch: [amd64, arm64, arm]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      env:
        GOOS: linux
        GOARCH: ${{ matric.arch }}
      run: go build -o ./bin/linux-${{ matric-arch }}/sc-bot ./cmd/
